### ISSUE TITLE
CSS polyfill

### ISSUE THREAD

**Issue by baptx** [neovov/Fullscreen-API-Polyfill#30]
Is it possible to make a polyfill for the fullscreen CSS rules?

**Comment by neovov** [comment]
No, that's not possible, you have to duplicate your rules with each browser vendor:

```css
#container:-moz-full-screen  { background: red; }
#container:-webkit-full-screen { background: red; }
#container:-ms-fullscreen { background: red; }
#container:fullscreen { background: red; }
```
